<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Translation\Translator;

class LangFrontendExportCommand extends Command
{
    /**
     * Locales bundled into the SPA.
     */
    private const LOCALES = ['en', 'ru', 'uk'];

    /**
     * Game sections actually consumed by the frontend bundle.
     * Extend this list (and re-run the command) when the SPA starts using
     * translations from another section.
     */
    private const FRONTEND_GAME_SECTIONS = ['BUI', 'LAB', 'RES', 'SPE'];

    protected $signature = 'tso:lang:export-frontend
        {--output-dir= : Override the output directory (used by tests)}';

    protected $description = 'Export UI + game translations to resources/js/lang/generated/<locale>.json for the SPA bundle';

    public function handle(Translator $translator): int
    {
        $outputDirectory = (string) ($this->option('output-dir') ?: resource_path('js/lang/generated'));

        if (! is_dir($outputDirectory) && ! mkdir($outputDirectory, 0755, true) && ! is_dir($outputDirectory)) {
            $this->error("Unable to create output directory: {$outputDirectory}");

            return self::FAILURE;
        }

        foreach (self::LOCALES as $locale) {
            $ui = $translator->get('ui', [], $locale, false);
            $ui = is_array($ui) ? $ui : [];
            ksort($ui, SORT_STRING);

            $gameCatalog = $translator->get('game', [], $locale, false);
            $gameCatalog = is_array($gameCatalog) ? $gameCatalog : [];

            $game = [];

            foreach (self::FRONTEND_GAME_SECTIONS as $section) {
                $entries = $gameCatalog[$section] ?? [];

                if (! is_array($entries)) {
                    $entries = [];
                }

                ksort($entries, SORT_STRING);
                $game[$section] = $entries;
            }

            ksort($game, SORT_STRING);

            $tasks = $translator->get('tasks', [], $locale, false);
            $tasks = is_array($tasks) ? $tasks : [];
            ksort($tasks, SORT_STRING);

            $payload = [
                '_generated' => 'DO NOT EDIT. Generated by "php artisan tso:lang:export-frontend".',
                'game' => $game,
                'locale' => $locale,
                'tasks' => $tasks,
                'ui' => $ui,
            ];

            $json = json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR)."\n";
            $target = rtrim($outputDirectory, '/')."/{$locale}.json";
            $temporary = $target.'.tmp.'.getmypid();

            if (file_put_contents($temporary, $json) === false || ! rename($temporary, $target)) {
                @unlink($temporary);
                $this->error("Unable to write {$target}");

                return self::FAILURE;
            }

            $this->info("Wrote {$target}");
        }

        return self::SUCCESS;
    }
}
