services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # Uses app_public volume to share public files with nginx
    volumes: !reset
      - app_public:/var/www/html/public
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - LOG_CHANNEL=stderr
    restart: unless-stopped

  nginx:
    ports: !override
      - "80:80"
      - "443:443"
    volumes: !override
      - app_public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-check-certificate --spider -q https://127.0.0.1/ || exit 1" ]

  node:
    profiles:
      - dev-only

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes: !reset []
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - LOG_CHANNEL=stderr
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes: !reset []
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - LOG_CHANNEL=stderr
    restart: unless-stopped

  postgres:
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports: !reset []

  redis:
    restart: unless-stopped
    ports: !reset []

volumes:
  app_public:
